maybe done task
htmlacademy-javascript/283531-kekstagram-26 pull request #3
Opened 2022-06-27 10:36 UTC by AnnaAyvazyan1

2022-06-27 19:43 UTC, PolinaShneider commented on index.html
> +  git push origin master
Я так понимаю, это случайно сюда попало. Давай удалим этот текст

2022-06-27 19:46 UTC, PolinaShneider commented on js/main.js
> +  return result[0];
Почему ты здесь возвращаешь `result[0]`?

2022-06-27 19:47 UTC, PolinaShneider requested changes
Точно ок работает генерация? У меня очень много всего undefined
<img width="540" alt="image" src="https://user-images.githubusercontent.com/15448200/176023505-e48ba32a-8e2a-4695-b4ae-e45ac7f1bd6f.png">

2022-06-28 07:59 UTC, AnnaAyvazyan1 commented on js/main.js
> +  return result[0];
splice возвращает мне array, a мне нужнo без array-a

2022-06-28 11:23 UTC, merged